# catalog.py

AUTO_PARTS_CATALOG = [
    {
        "brand": "Toyota",
        "model": "Corolla",
        "year": 2015,
        "category": "Тормозная система",
        "part_name": "Тормозные колодки передние",
        "sku": "TOY-COR-2015-BRK-FR",
        "price": 50,
        "currency": "USD",
        "stock": 12,
        "oem": "04465-02530",
        "compatibility_notes": "Подходит для Toyota Corolla 1.6, 1.8 (2013-2017 гг.)",
    },
    {
        "brand": "Toyota",
        "model": "Corolla",
        "year": 2015,
        "category": "Фильтры",
        "part_name": "Масляный фильтр",
        "sku": "TOY-COR-2015-OIL-FLT",
        "price": 12,
        "currency": "USD",
        "stock": 30,
        "oem": "90915-YZZE1",
        "compatibility_notes": "Оригинальный масляный фильтр для бензиновых двигателей",
    },
    {
        "brand": "Toyota",
        "model": "Camry",
        "year": 2018,
        "category": "Фильтры",
        "part_name": "Воздушный фильтр",
        "sku": "TOY-CAM-2018-AIR-FLT",
        "price": 18,
        "currency": "USD",
        "stock": 20,
        "oem": "17801-0H050",
        "compatibility_notes": "Подходит для Toyota Camry 2.5 (2017-2019 гг.)",
    },
    {
        "brand": "Toyota",
        "model": "Camry",
        "year": 2018,
        "category": "Масла и жидкости",
        "part_name": "Моторное масло 5W-30 (4 л)",
        "sku": "TOY-CAM-2018-OIL-5W30-4L",
        "price": 45,
        "currency": "USD",
        "stock": 8,
        "oem": "08880-80845",
        "compatibility_notes": "Рекомендуется для бензиновых двигателей Toyota",
    },
    {
        "brand": "BMW",
        "model": "3 Series",
        "year": 2019,
        "category": "Фильтры",
        "part_name": "Воздушный фильтр",
        "sku": "BMW-3S-2019-AIR-FLT",
        "price": 35,
        "currency": "EUR",
        "stock": 10,
        "oem": "13717605638",
        "compatibility_notes": "Подходит для BMW 320i/330i (G20)",
    },
    {
        "brand": "BMW",
        "model": "3 Series",
        "year": 2019,
        "category": "Тормозная система",
        "part_name": "Тормозные диски передние (комплект)",
        "sku": "BMW-3S-2019-DSK-FR",
        "price": 210,
        "currency": "EUR",
        "stock": 5,
        "oem": "34116883561",
        "compatibility_notes": "Оригинальные передние тормозные диски",
    },
    {
        "brand": "Volkswagen",
        "model": "Golf",
        "year": 2016,
        "category": "Подвеска",
        "part_name": "Амортизатор передний левый",
        "sku": "VW-GLF-2016-SUS-FL",
        "price": 90,
        "currency": "EUR",
        "stock": 7,
        "oem": "5Q0413031BK",
        "compatibility_notes": "Подходит для VW Golf VII (2012-2017 гг.)",
    },
    {
        "brand": "Volkswagen",
        "model": "Golf",
        "year": 2016,
        "category": "Фильтры",
        "part_name": "Салонный фильтр угольный",
        "sku": "VW-GLF-2016-CAB-FLT",
        "price": 20,
        "currency": "EUR",
        "stock": 25,
        "oem": "5Q0819653",
        "compatibility_notes": "Для автомобилей с кондиционером и климат-контролем",
    },
]